import {Character} from "../model/Character.model"
export const characters:Character[] = [
  {
    editable: false,
    _id: 6,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/%27Olu_Mel",
    name: "'Olu Mel",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/6/61/Olu_main.png",
    createdAt: "2021-04-12T01:25:09.759Z",
    updatedAt: "2021-12-20T20:39:18.031Z",
    url: "https://api.disneyapi.dev/characters/6",
    __v: 0,
  },
  {
    editable: false,
    _id: 7,
    films: [],
    shortFilms: [],
    tvShows: ["Gravity Falls"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/.GIFfany",
    name: ".GIFfany",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/5/51/Giffany.png",
    createdAt: "2021-04-12T01:25:10.354Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/7",
    __v: 0,
  },
  {
    editable: false,
    _id: 10,
    films: [],
    shortFilms: [],
    tvShows: ["Lilo & Stitch: The Series", "Stitch!"],
    videoGames: ["Disney Tsum Tsum (game)"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/627",
    name: "627",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/8/80/Profile_-_627.png",
    createdAt: "2021-04-12T01:25:58.961Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/10",
    __v: 0,
  },
  {
    editable: false,
    _id: 11,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: ["The Timekeeper"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/9-Eye",
    name: "9-Eye",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/7/77/9-eye.jpg",
    createdAt: "2021-04-12T01:25:59.785Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/11",
    __v: 0,
  },
  {
    editable: false,
    _id: 12,
    films: [],
    shortFilms: [],
    tvShows: ["Pickle and Peanut"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl:
      "https://disney.fandom.com/wiki/90%27s_Adventure_Bear_(character)",
    name: "90's Adventure Bear",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/3/3f/90%27s_Adventure_Bear_profile.png",
    createdAt: "2021-04-12T01:26:00.335Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/12",
    __v: 0,
  },
  {
    editable: false,
    _id: 13,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: ["Epic Mickey 2: The Power of Two"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/A.B.E.",
    name: "A.B.E.",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/2/20/ABE.jpg",
    createdAt: "2021-04-12T01:26:00.848Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/13",
    __v: 0,
  },
  {
    editable: false,
    _id: 14,
    films: [
      "The Computer Wore Tennis Shoes",
      "Now You See Him, Now You Don't",
      "The Strongest Man in the World",
    ],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/A.J._Arno",
    name: "A.J. Arno",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/2/2c/A.J._Arno.jpg",
    createdAt: "2021-04-12T01:26:01.358Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/14",
    __v: 0,
  },
  {
    editable: false,
    _id: 15,
    films: [],
    shortFilms: [],
    tvShows: ["Puppy Dog Pals"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/A.R.F._(character)",
    name: "A.R.F.",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/b/ba/A.R.F.png",
    createdAt: "2021-04-12T01:26:01.871Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/15",
    __v: 0,
  },
  {
    editable: false,
    _id: 16,
    films: ["Cheetah"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Abdullah",
    name: "Abdullah",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/cb/1087603-44532-clp-950.jpg",
    createdAt: "2021-04-12T01:26:02.377Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/16",
    __v: 0,
  },
  {
    editable: false,
    _id: 17,
    films: [],
    shortFilms: [],
    tvShows: ["The Legend of Tarzan"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Abigail_Markham",
    name: "Abigail Markham",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/9/95/Abigail_Markham.jpeg",
    createdAt: "2021-04-12T01:26:02.898Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/17",
    __v: 0,
  },
  {
    editable: false,
    _id: 18,
    films: ["The Fox and the Hound", "The Fox and the Hound 2"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Abigail_the_Cow",
    name: "Abigail the Cow",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/0/05/Fox-disneyscreencaps_com-901.jpg",
    createdAt: "2021-04-12T01:26:03.413Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/18",
    __v: 0,
  },
  {
    editable: false,
    _id: 19,
    films: [],
    shortFilms: [],
    tvShows: ["Once Upon a Time"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Princess_Abigail",
    name: "Abigail",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/d/dd/Regalblond.jpg",
    createdAt: "2021-04-12T01:26:03.961Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/19",
    __v: 0,
  },
  {
    editable: false,
    _id: 20,
    films: [],
    shortFilms: [],
    tvShows: ["Elena of Avalor"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Queen_Abigail",
    name: "Queen Abigail",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/f/fa/Normal_EoA_S3_E4_0217.jpg",
    createdAt: "2021-04-12T01:26:04.489Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/20",
    __v: 0,
  },
  {
    editable: false,
    _id: 21,
    films: ["The Return of Jafar", "Aladdin and the King of Thieves"],
    shortFilms: [],
    tvShows: ["Aladdin (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Abis_Mal%27s_Thugs",
    name: "Abis Mal's Thugs",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/b/ba/Abis_Mal%27s_Thugs.jpg",
    createdAt: "2021-04-12T01:26:05.081Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/21",
    __v: 0,
  },
  {
    editable: false,
    _id: 22,
    films: [],
    shortFilms: [],
    tvShows: ["Tron: Uprising"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Able",
    name: "Able",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/a/af/Able.png",
    createdAt: "2021-04-12T01:26:05.606Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/22",
    __v: 0,
  },
  {
    editable: false,
    _id: 23,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: ["Tron: Evolution"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Abraxas",
    name: "Abraxas",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/ce/Abraxas.jpg",
    createdAt: "2021-04-12T01:26:06.129Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/23",
    __v: 0,
  },
  {
    editable: false,
    _id: 24,
    films: [
      "Alice in Wonderland (2010 film)",
      "Alice Through the Looking Glass",
    ],
    shortFilms: [],
    tvShows: [],
    videoGames: [
      "Alice in Wonderland (2010 video game)",
      "Disney Universe",
      "Disney Crossy Road",
    ],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Absolem",
    name: "Absolem",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/4/4d/Caterpillar.jpg",
    createdAt: "2021-04-12T01:26:06.968Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/24",
    __v: 0,
  },
  {
    editable: false,
    _id: 25,
    films: [
      "Aladdin (film)",
      "The Return of Jafar",
      "Aladdin and the King of Thieves",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Disney Princess Enchanted Tales: Follow Your Dreams",
      "Aladdin (2019 film)",
    ],
    shortFilms: [],
    tvShows: ["Aladdin (TV series)", "Hercules (TV series)", "House of Mouse"],
    videoGames: [
      "Aladdin (video game)",
      "Disney's ReadingQuest With Aladdin",
      "Disney's MathQuest With Aladdin",
      "Disney's Aladdin in Nasira's Revenge",
      "Kingdom Hearts (series)",
      "Disney Universe",
      "Disney Princess Enchanting Storybooks",
      "Epic Mickey: Power of Illusion",
      "disney:Hidden Worlds",
      "Disney Infinity (series)",
      "Disney Villains Challenge",
      "Disney Tsum Tsum (game)",
      "Disney Crossy Road",
      "Disney Magic Kingdoms",
      "Disney Emoji Blitz",
      "Disney Getaway Blast",
      "Disney Princess Majestic Quest",
    ],
    parkAttractions: [
      "Garden of the Twelve Friends",
      "Voyage to the Crystal Grotto",
    ],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Abu",
    name: "Abu",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/3/3f/Profile_-_Abu.png",
    createdAt: "2021-04-12T01:26:07.701Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/25",
    __v: 0,
  },
  {
    editable: false,
    _id: 26,
    films: [],
    shortFilms: [],
    tvShows: ["Gravity Falls"],
    videoGames: ["Gravity Falls: Legend of the Gnome Gemulets"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Abuelita",
    name: "Abuelita",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/cd/Profile_-_Abuelita.png",
    createdAt: "2021-04-12T01:26:08.444Z",
    updatedAt: "2021-12-20T20:39:18.032Z",
    url: "https://api.disneyapi.dev/characters/26",
    __v: 0,
  },
  {
    editable: false,
    _id: 27,
    films: [],
    shortFilms: [],
    tvShows: ["Handy Manny"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Abuelito",
    name: "Abuelito",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/c8/Char_51942_thumb.jpg",
    createdAt: "2021-04-12T01:26:09.721Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/27",
    __v: 0,
  },
  {
    editable: false,
    _id: 28,
    films: [],
    shortFilms: [],
    tvShows: ["Big Hero 6: The Series"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/AC_and_DC",
    name: "AC and DC",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/7/75/Profile_-_AC_and_DC.jpg",
    createdAt: "2021-04-12T01:26:11.140Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/28",
    __v: 0,
  },
  {
    editable: false,
    _id: 29,
    films: [],
    shortFilms: [],
    tvShows: ["Kim Possible"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Professor_Acari",
    name: "Professor Acari",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/5/5d/Professor_Acari.jpg",
    createdAt: "2021-04-12T01:26:12.267Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/29",
    __v: 0,
  },
  {
    editable: false,
    _id: 30,
    films: ["Leroy & Stitch"],
    shortFilms: [],
    tvShows: ["Lilo & Stitch: The Series", "Stitch!"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Ace",
    name: "Ace",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/1/1e/Profile_-_Ace.png",
    createdAt: "2021-04-12T01:26:12.818Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/30",
    __v: 0,
  },
  {
    editable: false,
    _id: 31,
    films: ["The Hunchback of Notre Dame", "The Hunchback of Notre Dame II"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Achilles",
    name: "Achilles",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/8/8f/Achilles_HOND.jpg",
    createdAt: "2021-04-12T01:26:13.342Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/31",
    __v: 0,
  },
  {
    editable: false,
    _id: 33,
    films: ["Aladdin (film)", "Aladdin (2019 film)"],
    shortFilms: [],
    tvShows: ["Once Upon a Time"],
    videoGames: ["Disney Crossy Road"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Prince_Achmed",
    name: "Prince Achmed",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/7/76/Aladdin-disneyscreencaps.com-1123.jpg",
    createdAt: "2021-04-12T01:26:14.514Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/33",
    __v: 0,
  },
  {
    editable: false,
    _id: 34,
    films: ["Saludos Amigos"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aconcagua",
    name: "Aconcagua",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/3/32/Saludos-Amigos-classic-disney-18407142-800-600.jpg",
    createdAt: "2021-04-12T01:26:15.033Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/34",
    __v: 0,
  },
  {
    editable: false,
    _id: 35,
    films: [],
    shortFilms: [],
    tvShows: ["Tron: Uprising"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Ada",
    name: "Ada",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/f/f9/Ada.png",
    createdAt: "2021-04-12T01:26:15.554Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/35",
    __v: 0,
  },
  {
    editable: false,
    _id: 36,
    films: [],
    shortFilms: [],
    tvShows: ["K.C. Undercover"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Candace_Adams",
    name: "Candace Adams",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/8/8b/Enemy_of_the_State_promo_3.jpg",
    createdAt: "2021-04-12T01:26:16.062Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/36",
    __v: 0,
  },
  {
    editable: false,
    _id: 37,
    films: [],
    shortFilms: [],
    tvShows: ["Dog With a Blog"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Gator_Adams",
    name: "Gator Adams",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/6/60/LeonaGatorAdams.jpg",
    createdAt: "2021-04-12T01:26:17.191Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/37",
    __v: 0,
  },
  {
    editable: false,
    _id: 38,
    films: [],
    shortFilms: [],
    tvShows: ["The Suite Life on Deck"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Addison",
    name: "Addison",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/0/05/Addison_from_slod.jpg",
    createdAt: "2021-04-12T01:26:17.719Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/38",
    __v: 0,
  },
  {
    editable: false,
    _id: 40,
    films: [],
    shortFilms: [],
    tvShows: ["Hannah Montana"],
    videoGames: ["Hannah Montana (video game)"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Amber_Addison",
    name: "Amber Addison",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/5/52/250px-Amber.jpg",
    createdAt: "2021-04-12T01:26:18.915Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/40",
    __v: 0,
  },
  {
    editable: false,
    _id: 41,
    films: ["Genius"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Claire_Addison",
    name: "Claire Addison",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/7/79/Claireaddison.jpeg",
    createdAt: "2021-04-12T01:26:19.421Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/41",
    __v: 0,
  },
  {
    editable: false,
    _id: 42,
    films: ["Mickey's Good Deed"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Adelbert",
    name: "Adelbert",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/2/21/Adelbert.jpg",
    createdAt: "2021-04-12T01:26:19.989Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/42",
    __v: 0,
  },
  {
    editable: false,
    _id: 43,
    films: [],
    shortFilms: ["Mickey's Good Deed"],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Adelbert%27s_Father",
    name: "Adelbert's Father",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/9/96/Adelbertsfather.jpg",
    createdAt: "2021-04-12T01:26:20.494Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/43",
    __v: 0,
  },
  {
    editable: false,
    _id: 44,
    films: [],
    shortFilms: [],
    tvShows: ["Tangled: The Series"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Adira",
    name: "Adira",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/f/fa/Adira_Tangled.jpeg",
    createdAt: "2021-04-12T01:26:21.037Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/44",
    __v: 0,
  },
  {
    editable: false,
    _id: 45,
    films: ["Mary Poppins (film)", "Mary Poppins Returns"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Admiral_Boom_and_Mr._Binnacle",
    name: "Admiral Boom and Mr. Binnacle",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/b/be/Marypoppins-disneyscreencaps_com-1086.jpg",
    createdAt: "2021-04-12T01:26:21.560Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/45",
    __v: 0,
  },
  {
    editable: false,
    _id: 46,
    films: [],
    shortFilms: [],
    tvShows: ["Miles from Tomorrowland"],
    videoGames: ["Miles from Tomorrowland: Missions"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Admirals_Watson_and_Crick",
    name: "Admirals Watson and Crick",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/c6/Admirals-Watson-and-Crick.png",
    createdAt: "2021-04-12T01:26:22.087Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/46",
    __v: 0,
  },
  {
    editable: false,
    _id: 47,
    films: [],
    shortFilms: [],
    tvShows: ["Hercules (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Adonis",
    name: "Adonis",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/c/ca/Adonis.jpg",
    createdAt: "2021-04-12T01:26:22.613Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/47",
    __v: 0,
  },
  {
    editable: false,
    _id: 48,
    films: [],
    shortFilms: [],
    tvShows: ["Star Darlings"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Adora",
    name: "Adora",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/6/6b/Profile-Adora.PNG",
    createdAt: "2021-04-12T01:26:23.126Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/48",
    __v: 0,
  },
  {
    editable: false,
    _id: 49,
    films: [],
    shortFilms: [],
    tvShows: ["Goldie & Bear"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Adorable_Norm",
    name: "Adorable Norm",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/6/64/Adorable_Norm.png",
    createdAt: "2021-04-12T01:26:23.685Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/49",
    __v: 0,
  },
  {
    editable: false,
    _id: 112,
    films: ["Hercules (film)"],
    shortFilms: [],
    tvShows: ["Hercules (TV series)"],
    videoGames: ["Kingdom Hearts III"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Achilles_(Hercules)",
    name: "Achilles",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/d/d3/Vlcsnap-2015-05-06-23h04m15s601.png",
    createdAt: "2021-04-12T01:31:30.547Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/112",
    __v: 0,
  },
  {
    editable: false,
    _id: 119,
    films: ["Zombies", "Zombies 2", "Zombies 3"],
    shortFilms: [],
    tvShows: ["Addison's Moonstone Mystery (page does not exist)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Addison_Wells",
    name: "Addison",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/e/e5/Addison%25_27s_More_Than_Cheer_%25_3F_Teaser_ZOMBIES_2_Disney_Channel.jpg",
    createdAt: "2021-04-12T01:31:34.911Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/119",
    __v: 0,
  },
  {
    editable: false,
    _id: 130,
    films: [],
    shortFilms: [],
    tvShows: ["Pair of Kings"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aerosol",
    name: "Aerosol",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/9/92/Screenshot_2016-09-08_at_10.18.27_PM.png",
    createdAt: "2021-04-12T01:31:42.036Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/130",
    __v: 0,
  },
  {
    editable: false,
    _id: 131,
    films: [],
    shortFilms: [],
    tvShows: ["Jessie (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Agatha_(Jessie)",
    name: "Agatha",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/4/40/J119.png",
    createdAt: "2021-04-12T01:31:42.673Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/131",
    __v: 0,
  },
  {
    editable: false,
    _id: 132,
    films: [],
    shortFilms: [],
    tvShows: ["Phineas and Ferb"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Agent_E",
    name: "Agent E",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/d/d4/Agent_E_salutes_Perry.jpg",
    createdAt: "2021-04-12T01:31:43.223Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/132",
    __v: 0,
  },
  {
    editable: false,
    _id: 133,
    films: [],
    shortFilms: [],
    tvShows: ["Lab Rats"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl:
      "https://disney.fandom.com/wiki/Agent_Gordon_(Parallel_Universe)",
    name: "Agent Gordon",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/5/51/Screenshot_2016-09-12_at_8.13.42_PM.png",
    createdAt: "2021-04-12T01:31:43.723Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/133",
    __v: 0,
  },
  {
    editable: false,
    _id: 134,
    films: [],
    shortFilms: [],
    tvShows: ["The Replacements"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Agent_K",
    name: "Agent K",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/8/88/The-replacements-kath-soucie-0.jpg",
    createdAt: "2021-04-12T01:31:44.249Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/134",
    __v: 0,
  },
  {
    editable: false,
    _id: 135,
    films: [],
    shortFilms: [],
    tvShows: ["Quack Pack"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Agent_X",
    name: "Agent X",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/e/ef/Agent_X.png",
    createdAt: "2021-04-12T01:31:44.897Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/135",
    __v: 0,
  },
  {
    editable: false,
    _id: 136,
    films: ["Bolt (film)"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Agent",
    name: "Agent",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/b/b2/Agent-%28Bolt%29.jpg",
    createdAt: "2021-04-12T01:31:45.428Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/136",
    __v: 0,
  },
  {
    editable: false,
    _id: 137,
    films: [],
    shortFilms: [],
    tvShows: ["Miles from Tomorrowland"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aggro",
    name: "Aggro",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/9/9c/Aggro.png",
    createdAt: "2021-04-12T01:31:45.983Z",
    updatedAt: "2021-12-20T20:39:18.033Z",
    url: "https://api.disneyapi.dev/characters/137",
    __v: 0,
  },
  {
    editable: false,
    _id: 138,
    films: ["Frozen", "Ralph Breaks the Internet", "Frozen II"],
    shortFilms: ["Olaf's Frozen Adventure"],
    tvShows: ["Once Upon a Time"],
    videoGames: [],
    parkAttractions: ["Frozen: Live at the Hyperion"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/King_Agnarr",
    name: "King Agnarr",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/6/63/Profile_-_King_Agnarr_Frozen_2.jpg",
    createdAt: "2021-04-12T01:31:46.567Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/138",
    __v: 0,
  },
  {
    editable: false,
    _id: 139,
    films: ["The Lion King", "The Lion King (2019 film)"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Ahadi",
    name: "Ahadi",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/b/b3/Ahadihead.png",
    createdAt: "2021-04-12T01:31:47.129Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/139",
    __v: 0,
  },
  {
    editable: false,
    _id: 140,
    films: [
      "Air Bud",
      "Air Bud: Golden Receiver",
      "Air Bud: World Pup",
      "Air Bud: Seventh Inning Fetch",
      "Air Bud: Spikes Back",
      "Air Buddies",
      "Snow Buddies",
      "Space Buddies",
      "Santa Buddies",
      "Ralph Breaks the Internet",
    ],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Air_Bud_(dog)",
    name: "Air Bud",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/3/3c/Buddy_%28Air_Bud%29.png",
    createdAt: "2021-04-12T01:31:47.646Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/140",
    __v: 0,
  },
  {
    editable: false,
    _id: 141,
    films: [],
    shortFilms: [],
    tvShows: ["TaleSpin", "DuckTales (2017 series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Air_Pirates",
    name: "Air Pirates",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/e/e1/Wallpaper_air_pirates_by_apmaddog-d3awjq1.jpg",
    createdAt: "2021-04-12T01:31:48.509Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/141",
    __v: 0,
  },
  {
    editable: false,
    _id: 142,
    films: [],
    shortFilms: [],
    tvShows: ["Adventures of the Gummi Bears"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Airiels",
    name: "Airiels",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/9/9e/Imgres33.jpg",
    alignment: "Bad",
    createdAt: "2021-04-12T01:31:49.189Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/142",
    __v: 0,
  },
  {
    editable: false,
    _id: 143,
    films: [],
    shortFilms: [],
    tvShows: ["The Lion Guard"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Ajabu",
    name: "Ajabu",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/8/89/Ajabu.png",
    createdAt: "2021-04-12T01:31:49.768Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/143",
    __v: 0,
  },
  {
    editable: false,
    _id: 144,
    films: ["Mickey's House of Villains"],
    shortFilms: ["Donald Duck and the Gorilla", "Duck Pimples"],
    tvShows: ["Mickey Mouse Works"],
    videoGames: ["Deep Duck Trouble"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Ajax_the_Gorilla",
    name: "Ajax the Gorilla",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/8/81/Pepito_el_Gorila.jpg",
    createdAt: "2021-04-12T01:31:50.596Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/144",
    __v: 0,
  },
  {
    editable: false,
    _id: 145,
    films: [],
    shortFilms: [],
    tvShows: ["The Proud Family"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Ajay",
    name: "Ajay",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/e/e3/Ajay.png",
    createdAt: "2021-04-12T01:31:51.113Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/145",
    __v: 0,
  },
  {
    editable: false,
    _id: 146,
    films: [],
    shortFilms: [],
    tvShows: ["Aladdin (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Ajed_Al-Gebraic",
    name: "Ajed Al-Gebraic",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/d/db/Algebraic.jpg",
    createdAt: "2021-04-12T01:31:51.659Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/146",
    __v: 0,
  },
  {
    editable: false,
    _id: 147,
    films: [],
    shortFilms: [],
    tvShows: ["Aladdin (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Akbar",
    name: "Akbar",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/6/69/Akbar.jpg",
    createdAt: "2021-04-12T01:31:52.203Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/147",
    __v: 0,
  },
  {
    editable: false,
    _id: 148,
    films: [
      "The Jungle Book",
      "The Jungle Book: Mowgli's Story",
      "The Jungle Book (2016 film)",
    ],
    shortFilms: [],
    tvShows: ["Jungle Cubs"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Akela",
    name: "Akela",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/c5/Jungle-book-disneyscreencaps.com-465.jpg",
    createdAt: "2021-04-12T01:31:52.784Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/148",
    __v: 0,
  },
  {
    editable: false,
    _id: 149,
    films: [],
    shortFilms: [],
    tvShows: ["DuckTales (2017 series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Akita",
    name: "Akita",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/4/42/Dr._Akita.png",
    createdAt: "2021-04-12T01:31:53.403Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/149",
    __v: 0,
  },
  {
    editable: false,
    _id: 150,
    films: [],
    shortFilms: [],
    tvShows: ["Can You Teach My Alligator Manners?"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Al",
    name: "Al",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/e/e1/Profile_-_Al.png",
    createdAt: "2021-04-12T01:31:54.220Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/150",
    __v: 0,
  },
  {
    editable: false,
    _id: 151,
    films: [],
    shortFilms: [],
    tvShows: ["Aladdin (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Al_Muddy",
    name: "Al Muddy",
    imageUrl: "https://static.wikia.nocookie.net/disney/images/1/1e/Md082.jpg",
    alignment: "Bad",
    createdAt: "2021-04-12T01:31:54.750Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/151",
    __v: 0,
  },
  {
    editable: false,
    _id: 152,
    films: [],
    shortFilms: [],
    tvShows: ["Aladdin (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Al_Muddy_Sultan",
    name: "Al Muddy Sultan",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/e/e0/Almuddyking.jpg",
    createdAt: "2021-04-12T01:31:55.281Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/152",
    __v: 0,
  },
  {
    editable: false,
    _id: 153,
    films: ["Elena and the Secret of Avalor"],
    shortFilms: [],
    tvShows: ["Elena of Avalor"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alacazar",
    name: "Alacazar",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/7/7d/Alakazar.jpg",
    createdAt: "2021-04-12T01:31:55.832Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/153",
    __v: 0,
  },
  {
    editable: false,
    _id: 154,
    films: ["Dinosaur"],
    shortFilms: [],
    tvShows: [],
    videoGames: ["Disney's Dinosaur (video game)"],
    parkAttractions: ["DINOSAUR"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aladar",
    name: "Aladar",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/8/8c/Aladar_profile.jpg",
    createdAt: "2021-04-12T01:31:56.351Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/154",
    __v: 0,
  },
  {
    editable: false,
    _id: 155,
    films: ["Dinosaur"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aladar%27s_Mother",
    name: "Aladar's Mother",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/5/5b/Dinosaur-disneyscreencaps.com-84.jpg",
    createdAt: "2021-04-12T01:31:57.050Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/155",
    __v: 0,
  },
  {
    editable: false,
    _id: 156,
    films: [
      "Aladdin (film)",
      "The Return of Jafar",
      "Aladdin and the King of Thieves",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Mickey's House of Villains",
      "The Lion King 1½",
      "Once Upon a Halloween",
      "Descendants 2",
      "Aladdin (2019 film)",
      "Aladdin 2 (live-action film)",
    ],
    shortFilms: [],
    tvShows: [
      "Aladdin (TV series)",
      "Hercules (TV series)",
      "House of Mouse",
      "A Poem Is...",
      "Once Upon a Time",
    ],
    videoGames: [
      "Aladdin (video game)",
      "Disney's Aladdin Chess Adventures",
      "Aladdin Magic Carpet Racing",
      "Disney's MathQuest With Aladdin",
      "Disney's ReadingQuest With Aladdin",
      "Disney's Aladdin in Nasira's Revenge",
      "Kingdom Hearts (series)",
      "Disney Universe",
      "Kinect Disneyland Adventures",
      "Epic Mickey: Power of Illusion",
      "Disney Magical World",
      "Hidden Worlds",
      "Disney Infinity (series)",
      "Disney Villains Challenge",
      "Disney Tsum Tsum (game)",
      "Disney Crossy Road",
      "Disney Emoji Blitz",
      "Disney Magical Dice",
      "Disney Magic Kingdoms",
      "Disney Heroes: Battle Mode",
      "Disney Getaway Blast",
      "Disney Princess Majestic Quest",
      "Disney Sorcerer's Arena",
      "w:c:justdance:Just Dance 2014",
      "w:c:justdance:Just Dance Now",
      "w:c:justdance:Just Dance Unlimited",
    ],
    parkAttractions: [
      "Mickey's PhilharMagic",
      "Mickey's Soundsational Parade",
      "It's a Small World",
      "World of Color",
      "Fantasmic!",
      "Mickey's Boo-to-You Halloween Parade",
      "Mickey's Once Upon a Christmastime Parade",
      "Aladdin's Royal Caravan",
      "A Christmas Fantasy Parade",
      "Mickey and the Wondrous Book",
      "Golden Fairytale Fanfare",
      "Voyage to the Crystal Grotto",
      "Happily Ever After (fireworks show)",
      "Wishes",
      "Remember... Dreams Come True",
    ],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aladdin_(character)",
    name: "Aladdin",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/b/bb/Profile_-_Aladdin.png",
    createdAt: "2021-04-12T01:31:57.819Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/156",
    __v: 0,
  },
  {
    editable: false,
    _id: 157,
    films: ["Freaky Friday (2003 film)"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alan_Coleman",
    name: "Alan Coleman",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/c0/Alan_Coleman.jpg",
    createdAt: "2021-04-12T01:31:58.659Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/157",
    __v: 0,
  },
  {
    editable: false,
    _id: 158,
    films: ["Robin Hood (film)"],
    shortFilms: [],
    tvShows: ["House of Mouse", "The Wonderful World of Mickey Mouse"],
    videoGames: [],
    parkAttractions: ["Garden of the Twelve Friends"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alan-A-Dale",
    name: "Alan-A-Dale",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/3/33/Alan_A_Dale.jpg",
    createdAt: "2021-04-12T01:31:59.523Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/158",
    __v: 0,
  },
  {
    editable: false,
    _id: 159,
    films: ["Mary Poppins (film)"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Uncle_Albert",
    name: "Uncle Albert",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/e/e6/18799-12276.gif",
    createdAt: "2021-04-12T01:32:00.603Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/159",
    __v: 0,
  },
  {
    editable: false,
    _id: 160,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: ["Jungle Cruise", "Skipper Canteen"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Albert_Awol",
    name: "Albert Awol",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/7/7c/Noimage.png",
    createdAt: "2021-04-12T01:32:01.110Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/160",
    __v: 0,
  },
  {
    editable: false,
    _id: 161,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: ["Mystic Manor"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Albert_the_Monkey",
    name: "Albert the Monkey",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/3/30/MM_-_Albert.jpg",
    createdAt: "2021-04-12T01:32:01.665Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/161",
    __v: 0,
  },
  {
    editable: false,
    _id: 162,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: ["Skipper Canteen", "Jungle Cruise"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alberta_Falls",
    name: "Alberta Falls",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/3/35/AlbertaFalls2021.jpg",
    createdAt: "2021-04-12T01:32:02.172Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/162",
    __v: 0,
  },
  {
    editable: false,
    _id: 163,
    films: ["Beverly Hills Chihuahua 2"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alberto_and_Antonio",
    name: "Alberto and Antonio",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/9/90/Alberto_and_Antonio21.jpg",
    createdAt: "2021-04-12T01:32:02.682Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/163",
    __v: 0,
  },
  {
    editable: false,
    _id: 164,
    films: [],
    shortFilms: [],
    tvShows: ["W.I.T.C.H. (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alchemy",
    name: "Alchemy",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/4/43/Alchemy_2.jpg",
    createdAt: "2021-04-12T01:32:03.619Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/164",
    __v: 0,
  },
  {
    editable: false,
    _id: 165,
    films: [],
    shortFilms: [],
    tvShows: ["DuckTales (2017 series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aletheia",
    name: "Aletheia",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/ca/Aletheia.PNG",
    createdAt: "2021-04-12T01:32:04.498Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/165",
    __v: 0,
  },
  {
    editable: false,
    _id: 166,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: ["Soarin'"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aletta",
    name: "Aletta",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/2/2b/Screen_Shot_2020-10-24_at_3.17.35_PM.png",
    createdAt: "2021-04-12T01:32:05.003Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/166",
    __v: 0,
  },
  {
    editable: false,
    _id: 167,
    films: ["The Little Mermaid II: Return to the Sea"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alex",
    name: "Alex",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/a/aa/Alex_merman.jpg",
    createdAt: "2021-04-12T01:32:05.532Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/167",
    __v: 0,
  },
  {
    editable: false,
    _id: 168,
    films: ["Lemonade Mouth"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alex_(Lemonade_Mouth)",
    name: "Alex",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/f/f7/Alex_%28Lemonade_Mouth%29.png",
    createdAt: "2021-04-12T01:32:06.345Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/168",
    __v: 0,
  },
  {
    editable: false,
    _id: 169,
    films: [],
    shortFilms: [],
    tvShows: ["The Mighty Ducks: Game Changers"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alex_Morrow",
    name: "Alex Morrow",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/0/06/Game_On_Promotional_Photos_1.jpeg",
    createdAt: "2021-04-12T01:32:06.872Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/169",
    __v: 0,
  },
  {
    editable: false,
    _id: 170,
    films: [],
    shortFilms: [],
    tvShows: ["Hercules (TV series)"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alexander_(Hercules)",
    name: "Alexander",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/e/e3/Alexander_the_Great_%28Hercules%29.png",
    createdAt: "2021-04-12T01:32:07.396Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/170",
    __v: 0,
  },
  {
    editable: false,
    _id: 171,
    films: [],
    shortFilms: [],
    tvShows: ["Big City Greens"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alexander_and_Terry",
    name: "Alexander and Terry",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/6/66/Alexander_and_Terry.png",
    createdAt: "2021-04-12T01:32:07.952Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/171",
    __v: 0,
  },
  {
    editable: false,
    _id: 172,
    films: [],
    shortFilms: [],
    tvShows: [],
    videoGames: ["Disney Crossy Road"],
    parkAttractions: ["The Haunted Mansion (attraction)"],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alexander_Nitrokoff",
    name: "Alexander Nitrokoff",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/b/b9/Alexander_Nitrokoff.png",
    createdAt: "2021-04-12T01:32:08.791Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/172",
    __v: 0,
  },
  {
    editable: false,
    _id: 173,
    films: [
      "Beverly Hills Chihuahua 2",
      "Beverly Hills Chihuahua 3: Viva la Fiesta",
    ],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Ali",
    name: "Ali",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/7/75/Char_80637.jpg",
    createdAt: "2021-04-12T01:32:09.609Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/173",
    __v: 0,
  },
  {
    editable: false,
    _id: 174,
    films: [
      "Alice in Wonderland (1951 film)",
      "Mickey's Magical Christmas: Snowed in at the House of Mouse",
      "Mickey's House of Villains",
      "Once Upon a Halloween",
      "Ralph Breaks the Internet",
    ],
    shortFilms: [],
    tvShows: [
      "Walt Disney anthology series",
      "The Mouse Factory",
      "Adventures in Wonderland",
      "House of Mouse",
      "A Poem Is...",
      "Once Upon a Time in Wonderland",
      "Once Upon a Time",
      "At Home With Olaf",
    ],
    videoGames: [
      "Mickey Mousecapade",
      "Disney's Villains' Revenge",
      "Alice in Wonderland (video game)",
      "Kingdom Hearts (series)",
      "Kinect Disneyland Adventures",
      "Disney Magical World",
      "Disney Infinity (series)",
      "Disney Tsum Tsum (game)",
      "Disney Emoji Blitz",
      "Disney Magical Dice",
      "Disney Magic Kingdoms",
      "Disney Heroes: Battle Mode",
    ],
    parkAttractions: [
      "Alice in Wonderland (Disneyland attraction)",
      "Alice's Curious Labyrinth",
      "Mad Tea Party",
      "Mickey Mouse Revue",
      "Walt Disney's Parade of Dreams",
      "Fantasmic!",
      "Main Street Electrical Parade",
      "SpectroMagic",
      "Celebrate a Dreams Come True Parade",
      "Disney Stars and Motorcars Parade",
      "Mickey's Boo-to-You Halloween Parade",
      "Mickey's Once Upon a Christmastime Parade",
      "Festival of Fantasy Parade",
      "Parade of the Stars",
      "Once Upon a Time (Tokyo Disneyland)",
      "Happiness is Here Parade",
      "Disney Stars on Parade",
      "Dreaming Up!",
    ],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alice",
    name: "Alice",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/7/75/Profile_-_Alice.jpeg",
    createdAt: "2021-04-12T01:32:10.486Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/174",
    __v: 0,
  },
  {
    editable: false,
    _id: 175,
    films: ["Alice Comedies"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alice_(Alice_Comedies)",
    name: "Alice",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/d/d6/16CF428C-4347-429F-AF9B-B683A1895CBE.png",
    createdAt: "2021-04-12T01:32:11.035Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/175",
    __v: 0,
  },
  {
    editable: false,
    _id: 176,
    films: ["Alice in Wonderland (1951 film)"],
    shortFilms: [],
    tvShows: ["Once Upon a Time in Wonderland", "Princess Academy"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alice%27s_Sister",
    name: "Alice's Sister",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/e/e4/Alice-in-wonderland-disneyscreencaps.com-8652.jpg",
    createdAt: "2021-04-12T01:32:12.085Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/176",
    __v: 0,
  },
  {
    editable: false,
    _id: 177,
    films: ["Rudyard Kipling's The Jungle Book"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alice,_Rose,_and_Margaret",
    name: "Alice, Rose, and Margaret",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/c/ca/AliceRoseMargaret.png",
    createdAt: "2021-04-12T01:32:12.626Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/177",
    __v: 0,
  },
  {
    editable: false,
    _id: 178,
    films: ["Chicken Little (film)"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Aliens_(Chicken_Little)",
    name: "Aliens",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/4/43/Th51TC4289.jpg",
    createdAt: "2021-04-12T01:32:13.247Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/178",
    __v: 0,
  },
  {
    editable: false,
    _id: 179,
    films: [],
    shortFilms: [],
    tvShows: ["Chip 'n Dale Rescue Rangers"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/All_Hands_and_Mr._Starfish",
    name: "All Hands and Mr. Starfish",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/d/de/All_hands_and_mr._starfish.png",
    createdAt: "2021-04-12T01:32:14.177Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/179",
    __v: 0,
  },
  {
    editable: false,
    _id: 180,
    films: ["The Story of Robin Hood and His Merrie Men"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Allan-a-Dale_(1952_character)",
    name: "Allan-a-Dale",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/1/14/Elton_Hayes_The_Story_of_Robin_Hood_and_His_Merrie_Men_%281952%29.jpg",
    createdAt: "2021-04-12T01:32:14.716Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/180",
    __v: 0,
  },
  {
    editable: false,
    _id: 181,
    films: [],
    shortFilms: [],
    tvShows: ["Chip 'n Dale Rescue Rangers"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Irwina_Allen",
    name: "Irwina Allen",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/4/48/Chip_%27n_Dale_Rescue_Rangers_109_Risky_Beesness_arsenaloyal_-_YouTube12.jpg",
    createdAt: "2021-04-12T01:32:15.300Z",
    updatedAt: "2021-12-20T20:39:18.877Z",
    url: "https://api.disneyapi.dev/characters/181",
    __v: 0,
  },
  {
    editable: false,
    _id: 182,
    films: ["The Aristocats"],
    shortFilms: [],
    tvShows: ["House of Mouse"],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alley_Cats",
    name: "Alley Cats",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/6/69/Aristocats-disneyscreencaps.com-6619.jpg",
    createdAt: "2021-04-12T01:32:15.816Z",
    updatedAt: "2021-12-20T20:39:18.878Z",
    url: "https://api.disneyapi.dev/characters/182",
    __v: 0,
  },
  {
    editable: false,
    _id: 183,
    films: ["Oliver & Company"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alley_Dogs",
    name: "Alley Dogs",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/5/5e/Oliver-disneyscreencaps.com-270.jpg",
    createdAt: "2021-04-12T01:32:16.333Z",
    updatedAt: "2021-12-20T20:39:18.878Z",
    url: "https://api.disneyapi.dev/characters/183",
    __v: 0,
  },
  {
    editable: false,
    _id: 184,
    films: [],
    shortFilms: [],
    tvShows: ["Where's My Water?: Swampy's Underground Adventures"],
    videoGames: ["Where's My Water?"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Allie",
    name: "Allie",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/9/92/Allie_In-game_Appearance.jpeg",
    createdAt: "2021-04-12T01:32:16.856Z",
    updatedAt: "2021-12-20T20:39:18.878Z",
    url: "https://api.disneyapi.dev/characters/184",
    __v: 0,
  },
  {
    editable: false,
    _id: 185,
    films: ["I'll Be Home for Christmas"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Allie_Henderson",
    name: "Allie Henderson",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/4/48/Alliehomeforxmas.jpg",
    createdAt: "2021-04-12T01:32:17.366Z",
    updatedAt: "2021-12-20T20:39:18.878Z",
    url: "https://api.disneyapi.dev/characters/185",
    __v: 0,
  },
  {
    editable: false,
    _id: 186,
    films: ["Fantasia", "Mickey's Twice Upon a Christmas"],
    shortFilms: [],
    tvShows: ["House of Mouse"],
    videoGames: ["Fantasia (video game)", "Disney Sports Football"],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Alligators",
    name: "Alligators",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/d/df/Fantasia-disneyscreencaps_com-8802.jpg",
    createdAt: "2021-04-12T01:32:17.904Z",
    updatedAt: "2021-12-20T20:39:18.878Z",
    url: "https://api.disneyapi.dev/characters/186",
    __v: 0,
  },
  {
    editable: false,
    _id: 187,
    films: ["Hocus Pocus"],
    shortFilms: [],
    tvShows: [],
    videoGames: [],
    parkAttractions: [],
    allies: [],
    enemies: [],
    sourceUrl: "https://disney.fandom.com/wiki/Allison_(Hocus_Pocus)",
    name: "Allison",
    imageUrl:
      "https://static.wikia.nocookie.net/disney/images/b/b5/Reg_6630_6.jpg",
    createdAt: "2021-04-12T01:32:18.441Z",
    updatedAt: "2021-12-20T20:39:18.878Z",
    url: "https://api.disneyapi.dev/characters/187",
    __v: 0,
  },
];
